server.port: 8084
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: transaction-service

spring.datasource:
  url: jdbc:postgresql://ec2-34-203-255-149.compute-1.amazonaws.com:5432/d8stre3k2j581
  username: wlypstdipfukeo
  password: 72e9d6fede755e1e908359048679951f0c9f734a0d1b295c86167c67fa63ef83

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.chisom: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:https://reloadly-eureka-server.herokuapp.com/eureka}
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    hostname: localhost


app:
  auth-service:
    loginUrl: https://reloadly-auth-server.herokuapp.com/oauth/token
    validateUrl: https://reloadly-auth-server.herokuapp.com/oauth/check_token?token=
    basicAuth: Basic dGVzdDp0ZW1w

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

transaction-server-health: https://reloadly-transaction-service.herokuapp.com/actuator/health

api:

  description: |
    ### Rest Endpoint for Transaction Microservice.
    add token Obtained during login to the header of every request to enable
    you access to the secured resource.

    ### Using swagger and Token
    To use the secured endpoints with swagger, click the Authorize button and
    add the token obtained during Login.
    e.g Bearer 'token-value'

  transaction:
    create:
      description: (For Service to Service use Only) do not use.

    get-user: get a transactions for a user
---
spring:
  datasource:
    url: jdbc:postgresql://postgres/transaction_db
    username: postgres
    password: postgres
  config:
    activate:
      on-profile: docker

server.port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

app:
  auth-service:
    loginUrl: http://auth-service:8082/oauth/token
    validateUrl: http://auth-service:8082/oauth/check_token?token=
    basicAuth: Basic dGVzdDp0ZW1w